import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, Check, ChevronRight, FileText, GitBranch, Github, Layers3, ShieldCheck, Sparkles, CircleAlert, Clock3, BookOpen, Play, Copy, CheckCheck} from 'lucide-react';
import '@fontsource/noto-sans-sc/400.css';
import './style.css';
const repo='https://github.com/zhuzhenxiang93-create/RAG';
const Badge=({children,tone=''})=><span className={'badge '+tone}>{children}</span>;
function App(){
 const [cases,setCases]=useState([]),[selected,setSelected]=useState(''),[fact,setFact]=useState(''),[date,setDate]=useState('2026-01-01'),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('lite'),[full,setFull]=useState(false),[tab,setTab]=useState('analysis'),[copied,setCopied]=useState(false),[configMessage,setConfigMessage]=useState('');
 useEffect(()=>{Promise.all([fetch('/api/cases').then(r=>r.json()),fetch('/api/capabilities').then(r=>r.json())]).then(([cs,cp])=>{setCases(cs);setFact(cs[0].fact);setSelected(cs[0].id);setFull(cp.full_configured);setConfigMessage(cp.configuration_message || '')}).catch(()=>setError('无法连接 API。请启动 backend，然后重试。'));},[]);
 function choose(c){setSelected(c.id);setFact(c.fact);setResult(null);setError('')}
 async function run(){setBusy(true);setResult(null);setError('');try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fact,as_of_date:date,mode})});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'请检查案情长度与日期格式。');setResult(data);}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(JSON.stringify(result,null,2));setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('浏览器无法访问剪贴板，可在 JSON 页签手动复制。')}}
 const lite=result && result.mode!=='Full Mode';
 return <><header><a className="brand" href="/"><span className="brandmark"><Layers3 size={23}/></span><strong>LegalMind<span>−RAG</span></strong></a><nav><a href={repo+'/blob/main/docs/architecture.md'} target="_blank" rel="noreferrer">Architecture <ArrowUpRight size={13}/></a><a href={repo+'/blob/main/docs/evaluation.md'} target="_blank" rel="noreferrer">Evaluation <ArrowUpRight size={13}/></a><a className="github" href={repo+'/tree/main'} target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a></nav></header>
 <main>{result?.execution_mode==='mock_api_contract'&&<div className="mock-notice" role="status">MOCK API CONTRACT PREVIEW · 合成接口测试数据 · 未调用百炼实时模型</div>}<section className="heading"><div><div className="eyebrow"><span/> RESEARCH WORKSPACE <span className="slash">/</span> CASE ANALYSIS</div><h1>From case facts to<br/><em>traceable evidence.</em></h1><p>Evidence-grounded criminal case analysis.<br className="mobile"/> Explore the reasoning workflow, inspect every source.</p></div><div className="headline-note"><ShieldCheck size={22}/><div><b>Built for transparency</b><p>Every result shows its sources,<br/>execution mode and limitations.</p></div></div></section>
 <section className="stats"><div><strong>120K<span>+</span></strong><small>Training cases</small></div><div><strong>202</strong><small>Charge labels</small></div><div><strong>91.50<span>%</span></strong><small>Validation Micro-F1</small></div><div className="stat-last"><GitBranch size={25}/><span><b>Evidence-grounded</b><small>Inspect the complete pipeline</small></span></div></section>
 <div className="workspace"><aside><section className="panel input-panel"><div className="panel-heading"><div><span className="step">01</span><h2>Case Facts</h2></div><FileText size={19}/></div><p className="muted">选择演示案件，探索不同的证据路径。</p><div className="presets">{cases.map(c=><button className={selected===c.id?'preset active':'preset'} key={c.id} onClick={()=>choose(c)}><span><b>{c.title}</b><small>{c.subtitle}</small></span><ChevronRight size={16}/></button>)}</div><label htmlFor="fact">Anonymized case facts <span>匿名化案情</span></label><textarea id="fact" value={fact} maxLength={8000} onChange={e=>{setFact(e.target.value);setSelected('');setResult(null)}}/><div className="field-note"><ShieldCheck size={12}/> 请勿输入真实姓名、证件号码或联系方式</div><div className="fields"><div><label htmlFor="date">As-of date</label><input id="date" type="date" value={date} onChange={e=>{setDate(e.target.value);setResult(null)}}/></div><div><label htmlFor="mode">Execution mode</label><select id="mode" value={mode} onChange={e=>{setMode(e.target.value);setResult(null)}}><option value="lite">Bailian API Demo</option><option value="full" disabled={!full}>Full {full?'':'· configure assets'}</option></select></div></div><button className="analyze" onClick={run} disabled={busy||fact.trim().length<5||!date}>{busy?<><span className="spinner"/> Analyzing evidence…</>:<><Sparkles size={17}/> Analyze Case <ArrowRight size={17}/></>}</button>{configMessage&&<div className="error" role="status">百炼配置待完成：{configMessage}</div>}{error&&<div className="error" role="alert">{error}</div>}<div className="mode-note"><span className="dot"/><div><b>{mode==='lite'?'Bailian API · precomputed classification':'Full Mode · external assets'}</b><p>{mode==='lite'?'Illustrative charge scores · BM25 + API Dense → RRF → API Reranker · Qwen-Plus. Configure backend .env.':'BF16 LoRA · local evidence indexes · configured generation API.'}</p></div></div></section><section className="small-note"><BookOpen size={18}/><div><b>A research prototype, with boundaries.</b><p>Synthetic demo cases. No legal advice.<br/>Training data is not redistributed.</p></div></section></aside>
 <div className="results"><div className="results-top"><div className="tabs"><button className={tab==='analysis'?'selected':''} onClick={()=>setTab('analysis')}>Analysis workspace</button><button className={tab==='json'?'selected':''} onClick={()=>setTab('json')}>Structured JSON</button></div>{result&&<button className="icon-button" title="Copy JSON" onClick={copy}>{copied?<CheckCheck size={16}/>:<Copy size={16}/>}</button>}</div>
 {!result?<section className="empty panel"><div className="empty-symbol"><Layers3 size={32}/></div><Badge tone="blue">EVIDENCE BEFORE CONCLUSIONS</Badge><h2>Your analysis starts with the facts.</h2><p>Choose a scenario and run the pipeline to inspect<br/>candidate charges, case matches and validation checks.</p><div className="empty-steps"><span><FileText size={17}/> Facts</span><ChevronRight size={15}/><span><GitBranch size={17}/> Evidence</span><ChevronRight size={15}/><span><ShieldCheck size={17}/> Validation</span></div><div className="empty-footer"><Play size={13}/> Try case 02 to explore uncertainty and competing charges</div></section>:tab==='json'||!lite?<section className="panel json"><h2>{lite?'Structured response':'Full pipeline response'}</h2><p className="muted">Actual runtime output · full validation and timing fields</p><pre>{JSON.stringify(result,null,2)}</pre></section>:<>
 <div className="run-status"><span><Check size={14}/> Pipeline completed <i>·</i> <Clock3 size={13}/> {result.elapsed_ms.toFixed(1)} ms <i>·</i> {result.execution_mode==='mock_api_contract'?'MOCK API CONTRACT PREVIEW':'Bailian API'}</span><Badge tone="amber">Human review required</Badge></div>
 <section className="panel charges"><div className="panel-heading"><div><h2>Candidate Charges</h2><Badge tone="blue">Precomputed / illustrative</Badge></div><span className="tiny">Threshold 0.50</span></div>{result.candidate_charges.length?result.candidate_charges.map((c,i)=><div className="charge" key={c.charge}><div><b>{c.charge}</b><span>{c.above_threshold?'Above demo threshold':'Below demo threshold'}</span></div><div className="meter"><div style={{width:c.confidence*100+'%',background:i===0?'#426be1':'#a6b7df'}}/></div><strong>{c.confidence.toFixed(2)}</strong></div>):<p className="muted">自定义输入没有预计算分数。请选择预置案件，或配置 Full Mode。</p>}<p className="footnote">These classification scores demonstrate the UI; they are not predictions from the trained checkpoint.</p></section>
 <section className="panel"><div className="panel-heading"><div><h2>Retrieved Cases</h2><Badge>{result.retrieved_cases.length} matches</Badge></div><span className="tiny">BM25 + Dense → RRF → Reranker</span></div><div className="case-grid">{result.retrieved_cases.map((h,i)=><article className="case-card" key={h.id}><div className="case-title"><b><span>0{i+1}</span> {h.id}</b><Badge>{h.charge}罪</Badge></div><p>{h.text}</p><div className="case-metrics"><span>Reranker score <b>{h.score.toFixed(4)}</b></span><span>BM25 / Dense <b>{h.source_scores?.bm25?.toFixed(2)} / {h.source_scores?.vector?.toFixed(3)}</b></span><span>RRF <b>{h.source_scores?.rrf?.toFixed(5)}</b></span><span>Illustrative sentence <b>{h.months} months</b></span><span>Illustrative fine <b>¥{h.fine.toLocaleString()}</b></span></div><small>Synthetic case · {h.evidence_id}</small></article>)}</div>{!result.retrieved_cases.length&&<p className="muted">Insufficient facts to retrieve charge-constrained evidence.</p>}<p className="footnote">Retrieval scores are ranking values, not probabilities. All case facts and outcomes here are invented.</p></section>
 <section className="panel legal"><div className="panel-heading"><div><h2>Legal Basis</h2><Badge tone="amber">Verification pending</Badge></div><BookOpen size={18}/></div>{result.legal_basis.map(s=><div className="statute" key={s.article}><div className="article-no"><small>ARTICLE</small><strong>{s.article}</strong></div><div><b>中华人民共和国刑法 · {s.charge}</b><p>{s.summary}</p><a href={s.source_url} target="_blank" rel="noreferrer">Recorded official source <ArrowUpRight size={12}/></a><span className="statute-status">Source & effective date unverified</span></div></div>)}{!result.legal_basis.length&&<p className="muted">No applicable legal basis established from this input.</p>}</section>
 <section className="panel analysis"><div className="panel-heading"><div><h2>Grounded Analysis</h2><Badge tone={result.generation.status==='fallback'?'amber':'blue'}>{result.generation.model} · {result.generation.status}</Badge></div></div><div className="review-banner"><CircleAlert size={20}/><div><b>Legal conclusions withheld</b><p>{result.analysis.refusal_reason}</p></div></div><h3>Cited case observations</h3>{result.analysis.analogous_cases.map((c,i)=><p key={i}>{c.claim} <small>{c.evidence_ids.join(', ')}</small></p>)}<h3>What to verify next</h3><ul>{result.analysis.missing_information.map(x=><li key={x}>{x}</li>)}</ul><details><summary>Inspect cited Evidence IDs <span>{result.evidence_ids.length}</span></summary><div className="ids">{result.evidence_ids.map(x=><code key={x}>{x}</code>)}</div><p className="footnote">Whitelist validation checks citation membership; it does not prove legal correctness.</p></details></section>
 <section className="panel"><div className="panel-heading"><div><h2>Safety & Reliability</h2></div><ShieldCheck size={19}/></div><div className="checks">{result.checks.map(c=><div className="check-row" key={c.name}><span className={'check-icon '+c.status}>{c.status==='pass'?<Check size={13}/>:<CircleAlert size={13}/>}</span><div><b>{c.name}</b><small>{c.detail}</small></div><Badge tone={c.status==='pass'?'green':'amber'}>{c.status==='pass'?'Passed':c.status==='review'?'Required':'Pending'}</Badge></div>)}</div></section>
 <section className="panel"><div className="panel-heading"><h2>Hybrid Retrieval · Stage Rankings</h2><Badge tone="green">{result.retrieval_trace.status}</Badge></div><p className="footnote">Dense: {result.retrieval_trace.embedding_model || 'Skipped'} · Reranker: {result.retrieval_trace.reranker_model || 'Skipped'}</p><div className="rankings">{['bm25','dense','rrf','reranker'].map(stage=><div key={stage}><h3>{stage.toUpperCase()}</h3>{(result.retrieval_trace[stage] || []).map(row=><p key={row.case_id}><span>{row.rank}. {row.case_id}</span><b>{row.score.toFixed(4)}</b></p>)}</div>)}</div></section><section className="panel trace"><div className="panel-heading"><div><h2>Pipeline Trace</h2><Badge>{result.trace.length} stages</Badge></div><GitBranch size={18}/></div><div>{result.trace.map((s,i)=><div className="trace-row" key={s.name}><span className="trace-index">{i+1}</span><div><b>{s.name}</b><p>{s.detail}</p></div><Badge tone={s.status==='live'?'green':'blue'}>{s.status}</Badge></div>)}</div></section>
 </>}
 </div></div><footer><span>LegalMind-RAG <i> / </i> Evidence-grounded criminal case analysis</span><span>Research / decision-support prototype, not legal advice.</span></footer></main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
